### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by JenabB** [denniskigen/react-weather#2]
when i try to npm install the result show Unexpected token < in JSON at position 0 and preload animation

**Comment by denniskigen** [comment]
Hey @JenabB, did you create an `.env.local` file at the root of your project with the following info: 

```
REACT_APP_API_URL = 'https://api.openweathermap.org/data/2.5'
REACT_APP_API_KEY = The API key you obtained from openweathermap.org
REACT_APP_ICON_URL = 'https://openweathermap.org/img/w'
```
