### ISSUE TITLE
I think settings button on navbar would look better

### ISSUE THREAD

**Issue by shreyshreyansh** [denniskigen/react-weather#8]
![Screenshot 2021-09-15 094910](https://user-images.githubusercontent.com/53744971/133370024-78b4220f-80e2-4844-8f98-2bbd8e6a2738.jpg)

**Comment by yung-coder** [comment]
@shreyshreyansh is this project still active

**Comment by shreyshreyansh** [comment]
@yung-coder Nope, feel free to take on 🚀
